from markdownify import markdownify as _markdownify


def quill_html_to_markdown(html: str) -> str:
    """Convert HTML generated by the Quill editor to Markdown.

    Parameters
    ----------
    html: str
        HTML string from the editor.

    Returns
    -------
    str
        Converted Markdown representation. Returns an empty string if ``html`` is
        falsy.
    """
    if not html:
        return ""
    return _markdownify(html)
